"{\n    \"buildkite_job_id\": \"018ef4db-3fca-4d8b-b24d-3216cd31f936\",\n    \"buildkite_url\": \"https://buildkite.com/ray-project/release/builds/13850#018ef4db-3fca-4d8b-b24d-3216cd31f936\",\n    \"cluster_id\": \"ses_svhdn1tfcnasljhwxewpb4l78u\",\n    \"cluster_url\": \"https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_svhdn1tfcnasljhwxewpb4l78u\",\n    \"extra_tags\": {\n        \"buildkite_job_id\": \"018ef4db-3fca-4d8b-b24d-3216cd31f936\",\n        \"buildkite_pipeline_slug\": \"release\",\n        \"buildkite_pull_request\": \"false\",\n        \"buildkite_source\": \"trigger_job\",\n        \"release_frequency\": \"nightly-3x\",\n        \"test_name\": \"many_pgs.aws\",\n        \"test_smoke_test\": \"False\"\n    },\n    \"job_id\": \"prodjob_lz5fkr5dzwsh6ay19qyqiq1u7c\",\n    \"job_url\": \"https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_lz5fkr5dzwsh6ay19qyqiq1u7c\",\n    \"last_logs\": \"bash: cannot set terminal process group (-1): Inappropriate ioctl for device\\nbash: no job control in this shell\\n[W 2024-04-18 23:21:09.537 ServerApp] jupyter_server_terminals | error adding extension (enabled: True): Jupyter Server Terminals requires Jupyter Server 2.0+\\n    Traceback (most recent call last):\\n      File \\\"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/extension/manager.py\\\", line 320, in add_extension\\n        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)\\n      File \\\"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/extension/manager.py\\\", line 166, in __init__\\n        super().__init__(*args, **kwargs)\\n      File \\\"/home/ray/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py\\\", line 1371, in __init__\\n        value = self._traits[key]._cross_validate(self, getattr(self, key))\\n      File \\\"/home/ray/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py\\\", line 732, in _cross_validate\\n        value = obj._trait_validators[self.name](obj, proposal)\\n      File \\\"/home/ray/anaconda3/lib/python3.9/site-packages/traitlets/traitlets.py\\\", line 1243, in __call__\\n        return self.func(*args, **kwargs)\\n      File \\\"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/extension/manager.py\\\", line 175, in _validate_name\\n        self._module, self._metadata = get_metadata(name)\\n      File \\\"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/extension/utils.py\\\", line 60, in get_metadata\\n        module = importlib.import_module(package_name)\\n      File \\\"/home/ray/anaconda3/lib/python3.9/importlib/__init__.py\\\", line 127, in import_module\\n        return _bootstrap._gcd_import(name[level:], package, level)\\n      File \\\"<frozen importlib._bootstrap>\\\", line 1030, in _gcd_import\\n      File \\\"<frozen importlib._bootstrap>\\\", line 1007, in _find_and_load\\n      File \\\"<frozen importlib._bootstrap>\\\", line 986, in _find_and_load_unlocked\\n      File \\\"<frozen importlib._bootstrap>\\\", line 680, in _load_unlocked\\n      File \\\"<frozen importlib._bootstrap_external>\\\", line 850, in exec_module\\n      File \\\"<frozen importlib._bootstrap>\\\", line 228, in _call_with_frames_removed\\n      File \\\"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server_terminals/__init__.py\\\", line 9, in <module>\\n        raise RuntimeError(\\\"Jupyter Server Terminals requires Jupyter Server 2.0+\\\")\\n    RuntimeError: Jupyter Server Terminals requires Jupyter Server 2.0+\\n[I 2024-04-18 23:21:09.756 ServerApp] jupyter_server_fileid | extension was successfully linked.\\n[I 2024-04-18 23:21:09.759 ServerApp] jupyter_server_ydoc | extension was successfully linked.\\n[W 2024-04-18 23:21:09.760 LabApp] 'allow_remote_access' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.\\n[W 2024-04-18 23:21:09.761 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.\\n[W 2024-04-18 23:21:09.761 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.\\n[W 2024-04-18 23:21:09.761 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.\\n[I 2024-04-18 23:21:09.763 ServerApp] jupyterlab | extension was successfully linked.\\n[I 2024-04-18 23:21:09.763 ServerApp] jupytext | extension was successfully linked.\\n[I 2024-04-18 23:21:09.767 ServerApp] nbclassic | extension was successfully linked.\\n[I 2024-04-18 23:21:09.767 ServerApp] Writing Jupyter server cookie secret to /home/ray/.local/share/jupyter/runtime/jupyter_cookie_secret\\n[I 2024-04-18 23:21:09.985 ServerApp] notebook_shim | extension was successfully linked.\\n[W 2024-04-18 23:21:10.005 ServerApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.\\n[I 2024-04-18 23:21:10.007 ServerApp] notebook_shim | extension was successfully loaded.\\n[I 2024-04-18 23:21:10.007 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager\\n[I 2024-04-18 23:21:10.007 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/ray/default\\n[I 2024-04-18 23:21:10.007 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/ray/.local/share/jupyter/file_id_manager.db\\n[I 2024-04-18 23:21:10.008 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.\\n[I 2024-04-18 23:21:10.008 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE\\n[I 2024-04-18 23:21:10.123 ServerApp] jupyter_server_fileid | extension was successfully loaded.\\n[I 2024-04-18 23:21:10.123 ServerApp] jupyter_server_ydoc | extension was successfully loaded.\\n[I 2024-04-18 23:21:10.126 LabApp] JupyterLab extension loaded from /home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab\\n[I 2024-04-18 23:21:10.126 LabApp] JupyterLab application directory is /home/ray/anaconda3/share/jupyter/lab\\n[I 2024-04-18 23:21:10.128 ServerApp] jupyterlab | extension was successfully loaded.\\n[I 2024-04-18 23:21:10.129 ServerApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager\\n[I 2024-04-18 23:21:10.130 ServerApp] jupytext | extension was successfully loaded.\\n[I 2024-04-18 23:21:10.133 ServerApp] nbclassic | extension was successfully loaded.\\n[I 2024-04-18 23:21:10.133 ServerApp] Serving notebooks from local directory: /home/ray/default\\n[I 2024-04-18 23:21:10.133 ServerApp] Jupyter Server 1.24.0 is running at:\\n[I 2024-04-18 23:21:10.133 ServerApp] http://127.0.0.1:8999/jupyter/lab\\n[I 2024-04-18 23:21:10.133 ServerApp]  or http://127.0.0.1:8999/jupyter/lab\\n[I 2024-04-18 23:21:10.133 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).\\n\",\n    \"results\": {\n        \"_dashboard_memory_usage_mb\": 130.555904,\n        \"_dashboard_test_success\": true,\n        \"_peak_memory\": 2.18,\n        \"_peak_process_memory\": \"PID\\tMEM\\tCOMMAND\\n151\\t0.93GiB\\t/home/ray/anaconda3/lib/python3.9/site-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/s\\n920\\t0.42GiB\\tpython distributed/test_many_pgs.py\\n266\\t0.14GiB\\t/home/ray/anaconda3/bin/python /home/ray/anaconda3/lib/python3.9/site-packages/ray/dashboard/dashboa\\n447\\t0.07GiB\\t/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/runti\\n739\\t0.07GiB\\tray::JobSupervisor\\n582\\t0.07GiB\\t/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/jupyter-lab --allow-root --ip=127.0.0.1 --no-\\n445\\t0.06GiB\\t/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.9/site-packages/ray/dashboard/agen\\n980\\t0.06GiB\\tray::MemoryMonitorActor.run\\n1068\\t0.05GiB\\tray::DashboardTester.run\\n365\\t0.04GiB\\t/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/log_m\",\n        \"num_pgs\": 1000,\n        \"perf_metrics\": [\n            {\n                \"perf_metric_name\": \"pgs_per_second\",\n                \"perf_metric_type\": \"THROUGHPUT\",\n                \"perf_metric_value\": 23.471191969494587\n            },\n            {\n                \"perf_metric_name\": \"dashboard_p50_latency_ms\",\n                \"perf_metric_type\": \"LATENCY\",\n                \"perf_metric_value\": 3.392\n            },\n            {\n                \"perf_metric_name\": \"dashboard_p95_latency_ms\",\n                \"perf_metric_type\": \"LATENCY\",\n                \"perf_metric_value\": 19.066\n            },\n            {\n                \"perf_metric_name\": \"dashboard_p99_latency_ms\",\n                \"perf_metric_type\": \"LATENCY\",\n                \"perf_metric_value\": 126.705\n            }\n        ],\n        \"pgs_per_second\": 23.471191969494587,\n        \"success\": \"1\",\n        \"time\": 42.60542035102844\n    },\n    \"return_code\": 0,\n    \"runtime\": 321.957653468,\n    \"smoke_test\": false,\n    \"stable\": true,\n    \"status\": \"success\",\n    \"wheels_url\": null\n}"
