{
    "buildkite_job_id": "018f422b-90c1-4378-a7db-7949f2dfb016",
    "buildkite_url": "https://buildkite.com/ray-project/release/builds/14871#018f422b-90c1-4378-a7db-7949f2dfb016",
    "cluster_id": "ses_hiudcdzmyacip3yunfjlu9vnx7",
    "cluster_url": "https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_hiudcdzmyacip3yunfjlu9vnx7",
    "extra_tags": {
        "buildkite_job_id": "018f422b-90c1-4378-a7db-7949f2dfb016",
        "buildkite_pipeline_slug": "release",
        "buildkite_pull_request": "false",
        "buildkite_source": "trigger_job",
        "release_frequency": "nightly",
        "test_name": "stress_test_many_tasks.aws",
        "test_smoke_test": "False"
    },
    "job_id": "prodjob_1b3y871zfaqaebhtrhelf5u81p",
    "job_url": "https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_1b3y871zfaqaebhtrhelf5u81p",
    "last_logs": "    from .handlers.announcements import (  # noqa\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/handlers/announcements.py\", line 14, in <module>\n    from jupyter_server.base.handlers import APIHandler\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n    from jupyter_events import EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n    from .logger import EVENTS_METADATA_VERSION, EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/logger.py\", line 19, in <module>\n    from .schema import SchemaType\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/schema.py\", line 9, in <module>\n    from referencing import Registry\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/__init__.py\", line 5, in <module>\n    from referencing._core import Anchor, Registry, Resource, Specification\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 86, in <module>\n    class Specification(Generic[D]):\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 112, in Specification\n    ] = field(alias=\"anchors_in\")\nTypeError: field() got an unexpected keyword argument 'alias'\nbash: cannot set terminal process group (-1): Inappropriate ioctl for device\nbash: no job control in this shell\nTraceback (most recent call last):\n  File \"/home/ray/anaconda3/bin/jupyter-lab\", line 5, in <module>\n    from jupyterlab.labapp import main\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/__init__.py\", line 7, in <module>\n    from .handlers.announcements import (  # noqa\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/handlers/announcements.py\", line 14, in <module>\n    from jupyter_server.base.handlers import APIHandler\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n    from jupyter_events import EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n    from .logger import EVENTS_METADATA_VERSION, EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/logger.py\", line 19, in <module>\n    from .schema import SchemaType\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/schema.py\", line 9, in <module>\n    from referencing import Registry\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/__init__.py\", line 5, in <module>\n    from referencing._core import Anchor, Registry, Resource, Specification\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 86, in <module>\n    class Specification(Generic[D]):\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 112, in Specification\n    ] = field(alias=\"anchors_in\")\nTypeError: field() got an unexpected keyword argument 'alias'\nbash: cannot set terminal process group (-1): Inappropriate ioctl for device\nbash: no job control in this shell\nTraceback (most recent call last):\n  File \"/home/ray/anaconda3/bin/jupyter-lab\", line 5, in <module>\n    from jupyterlab.labapp import main\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/__init__.py\", line 7, in <module>\n    from .handlers.announcements import (  # noqa\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/handlers/announcements.py\", line 14, in <module>\n    from jupyter_server.base.handlers import APIHandler\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n    from jupyter_events import EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n    from .logger import EVENTS_METADATA_VERSION, EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/logger.py\", line 19, in <module>\n    from .schema import SchemaType\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/schema.py\", line 9, in <module>\n    from referencing import Registry\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/__init__.py\", line 5, in <module>\n    from referencing._core import Anchor, Registry, Resource, Specification\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 86, in <module>\n    class Specification(Generic[D]):\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 112, in Specification\n    ] = field(alias=\"anchors_in\")\nTypeError: field() got an unexpected keyword argument 'alias'\nbash: cannot set terminal process group (-1): Inappropriate ioctl for device\nbash: no job control in this shell\nTraceback (most recent call last):\n  File \"/home/ray/anaconda3/bin/jupyter-lab\", line 5, in <module>\n    from jupyterlab.labapp import main\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/__init__.py\", line 7, in <module>\n    from .handlers.announcements import (  # noqa\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/handlers/announcements.py\", line 14, in <module>\n    from jupyter_server.base.handlers import APIHandler\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n    from jupyter_events import EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n    from .logger import EVENTS_METADATA_VERSION, EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/logger.py\", line 19, in <module>\n    from .schema import SchemaType\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/schema.py\", line 9, in <module>\n    from referencing import Registry\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/__init__.py\", line 5, in <module>\n    from referencing._core import Anchor, Registry, Resource, Specification\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 86, in <module>\n    class Specification(Generic[D]):\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 112, in Specification\n    ] = field(alias=\"anchors_in\")\nTypeError: field() got an unexpected keyword argument 'alias'\n",
    "results": {
        "perf_metrics": [
            {
                "perf_metric_name": "stage_0_time",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 11.001468896865845
            },
            {
                "perf_metric_name": "stage_1_avg_iteration_time",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 24.483961820602417
            },
            {
                "perf_metric_name": "stage_2_avg_iteration_time",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 53.381308794021606
            },
            {
                "perf_metric_name": "stage_3_creation_time",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 2.0290634632110596
            },
            {
                "perf_metric_name": "stage_3_time",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 3010.209487915039
            },
            {
                "perf_metric_name": "stage_4_spread",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 0.6472558249100075
            }
        ],
        "stage_0_time": 11.001468896865845,
        "stage_1_avg_iteration_time": 24.483961820602417,
        "stage_1_max_iteration_time": 25.398903131484985,
        "stage_1_min_iteration_time": 23.48150372505188,
        "stage_1_time": 244.83970546722412,
        "stage_2_avg_iteration_time": 53.381308794021606,
        "stage_2_max_iteration_time": 54.12904739379883,
        "stage_2_min_iteration_time": 52.89454412460327,
        "stage_2_time": 266.9073483943939,
        "stage_3_creation_time": 2.0290634632110596,
        "stage_3_time": 3010.209487915039,
        "stage_4_spread": 0.6472558249100075,
        "success": 1
    },
    "return_code": 0,
    "runtime": 4155.819861022001,
    "smoke_test": false,
    "stable": true,
    "status": "success",
    "wheels_url": null
}
