{
    "buildkite_job_id": "018f422b-90d0-48d2-bccf-f16a245b6385",
    "buildkite_url": "https://buildkite.com/ray-project/release/builds/14871#018f422b-90d0-48d2-bccf-f16a245b6385",
    "cluster_id": "ses_4g8f39dgsnc1p7b9aix2l8iw74",
    "cluster_url": "https://console.anyscale-staging.com/o/anyscale-internal/projects/prj_qC3ZfndQWYYjx2cz8KWGNUL4/clusters/ses_4g8f39dgsnc1p7b9aix2l8iw74",
    "extra_tags": {
        "buildkite_job_id": "018f422b-90d0-48d2-bccf-f16a245b6385",
        "buildkite_pipeline_slug": "release",
        "buildkite_pull_request": "false",
        "buildkite_source": "trigger_job",
        "release_frequency": "nightly",
        "test_name": "stress_test_placement_group.aws",
        "test_smoke_test": "False"
    },
    "job_id": "prodjob_pyabb785ae52hhbcypi8ju7ddr",
    "job_url": "https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_pyabb785ae52hhbcypi8ju7ddr",
    "last_logs": "    from .handlers.announcements import (  # noqa\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/handlers/announcements.py\", line 14, in <module>\n    from jupyter_server.base.handlers import APIHandler\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n    from jupyter_events import EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n    from .logger import EVENTS_METADATA_VERSION, EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/logger.py\", line 19, in <module>\n    from .schema import SchemaType\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/schema.py\", line 9, in <module>\n    from referencing import Registry\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/__init__.py\", line 5, in <module>\n    from referencing._core import Anchor, Registry, Resource, Specification\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 86, in <module>\n    class Specification(Generic[D]):\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 112, in Specification\n    ] = field(alias=\"anchors_in\")\nTypeError: field() got an unexpected keyword argument 'alias'\nbash: cannot set terminal process group (-1): Inappropriate ioctl for device\nbash: no job control in this shell\nTraceback (most recent call last):\n  File \"/home/ray/anaconda3/bin/jupyter-lab\", line 5, in <module>\n    from jupyterlab.labapp import main\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/__init__.py\", line 7, in <module>\n    from .handlers.announcements import (  # noqa\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/handlers/announcements.py\", line 14, in <module>\n    from jupyter_server.base.handlers import APIHandler\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n    from jupyter_events import EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n    from .logger import EVENTS_METADATA_VERSION, EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/logger.py\", line 19, in <module>\n    from .schema import SchemaType\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/schema.py\", line 9, in <module>\n    from referencing import Registry\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/__init__.py\", line 5, in <module>\n    from referencing._core import Anchor, Registry, Resource, Specification\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 86, in <module>\n    class Specification(Generic[D]):\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 112, in Specification\n    ] = field(alias=\"anchors_in\")\nTypeError: field() got an unexpected keyword argument 'alias'\nbash: cannot set terminal process group (-1): Inappropriate ioctl for device\nbash: no job control in this shell\nTraceback (most recent call last):\n  File \"/home/ray/anaconda3/bin/jupyter-lab\", line 5, in <module>\n    from jupyterlab.labapp import main\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/__init__.py\", line 7, in <module>\n    from .handlers.announcements import (  # noqa\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/handlers/announcements.py\", line 14, in <module>\n    from jupyter_server.base.handlers import APIHandler\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n    from jupyter_events import EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n    from .logger import EVENTS_METADATA_VERSION, EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/logger.py\", line 19, in <module>\n    from .schema import SchemaType\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/schema.py\", line 9, in <module>\n    from referencing import Registry\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/__init__.py\", line 5, in <module>\n    from referencing._core import Anchor, Registry, Resource, Specification\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 86, in <module>\n    class Specification(Generic[D]):\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 112, in Specification\n    ] = field(alias=\"anchors_in\")\nTypeError: field() got an unexpected keyword argument 'alias'\nbash: cannot set terminal process group (-1): Inappropriate ioctl for device\nbash: no job control in this shell\nTraceback (most recent call last):\n  File \"/home/ray/anaconda3/bin/jupyter-lab\", line 5, in <module>\n    from jupyterlab.labapp import main\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/__init__.py\", line 7, in <module>\n    from .handlers.announcements import (  # noqa\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyterlab/handlers/announcements.py\", line 14, in <module>\n    from jupyter_server.base.handlers import APIHandler\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_server/base/handlers.py\", line 24, in <module>\n    from jupyter_events import EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/__init__.py\", line 3, in <module>\n    from .logger import EVENTS_METADATA_VERSION, EventLogger\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/logger.py\", line 19, in <module>\n    from .schema import SchemaType\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/jupyter_events/schema.py\", line 9, in <module>\n    from referencing import Registry\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/__init__.py\", line 5, in <module>\n    from referencing._core import Anchor, Registry, Resource, Specification\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 86, in <module>\n    class Specification(Generic[D]):\n  File \"/home/ray/anaconda3/lib/python3.9/site-packages/referencing/_core.py\", line 112, in Specification\n    ] = field(alias=\"anchors_in\")\nTypeError: field() got an unexpected keyword argument 'alias'\n",
    "results": {
        "avg_pg_create_time_ms": 0.889821163662783,
        "avg_pg_remove_time_ms": 0.9000654909906795,
        "perf_metrics": [
            {
                "perf_metric_name": "avg_pg_create_time_ms",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 0.889821163662783
            },
            {
                "perf_metric_name": "avg_pg_remove_time_ms",
                "perf_metric_type": "LATENCY",
                "perf_metric_value": 0.9000654909906795
            }
        ],
        "success": 1
    },
    "return_code": 0,
    "runtime": 668.5270132449999,
    "smoke_test": false,
    "stable": true,
    "status": "success",
    "wheels_url": null
}
